INSERT INTO questions (text, next_due, autogenerated, model_type, created_at, updated_at) 
VALUES ('What size are the angles in an equilateral triangle?', '2023-07-22 12:00:00', FALSE, 'gpt-4', NOW(), NOW());

INSERT INTO question_answers (question_id, answered_correctly, answer_date, ease, created_at, updated_at) 
VALUES (1, TRUE, '2023-07-22 12:00:00', 3, NOW(), NOW());

INSERT INTO tags (name, created_at, updated_at) 
VALUES ('trigonometry', NOW(), NOW());

INSERT INTO question_tag (question_id, tag_id, created_at, updated_at) 
VALUES (1, 1, NOW(), NOW());
